### PR TITLE
Fix method of obtaining service account token

### LINKED ISSUE #306: Setup instructions assume presence of an auto-generated service account token
The .secrets field within service accounts is only for listing secrets
to be mounted into pods, not for extracting secrets for other uses.
There is no guarantee the first item in the list will be a token secret.

In Kubernetes 1.24+, this field is not populated by default.

Adapt instructions from https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token to obtain a token

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #306

#### Description

The .secrets field within service accounts is only for listing secrets
to be mounted into pods, not for extracting secrets for other uses.
There is no guarantee the first item in the list will be a token secret.

In 1.24+, this field is not populated by default.

#### Change summary
Adapt instructions from https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token to obtain a token

cc @zshihang

### CODE REVIEW

File: anthos-bm-gcp-terraform/resources/login.sh [hunk 1]
```diff
@@ -50,8 +50,24 @@ kubectl create clusterrolebinding another-binding \
   --clusterrole cluster-admin --serviceaccount default:edga-sa
```
Comment (Shabirmean) [inline anthos-bm-gcp-terraform/resources/login.sh:50]: I know it's out of scope; if possible can update
- line 17: `edga-sa` -> `edge-sa`
- line 50 as well to use: ${KSA_NAME} instead of `edga-sa`?

File: anthos-bm-openstack-terraform/resources/abm_cluster_login.sh [hunk 2]
```diff
@@ -48,11 +48,27 @@ kubectl create clusterrolebinding edge-sa-view-binding \
 kubectl create clusterrolebinding edge-sa-console-reader-binding \
   --clusterrole cloud-console-reader --serviceaccount default:${KSA_NAME}
 kubectl create clusterrolebinding another-binding \
-  --clusterrole cluster-admin --serviceaccount default:edga-sa
+  --clusterrole cluster-admin --serviceaccount default:${KSA_NAME}
```
Comment (Shabirmean) [inline anthos-bm-openstack-terraform/resources/abm_cluster_login.sh:51]: Can you update line 18: `edga-sa` -> `edge-sa`

File: anthos-bm-edge-deployment/scripts/cloud/cnuc-k8s-login-setup.sh [hunk 3]
```diff
@@ -48,11 +48,27 @@ kubectl create clusterrolebinding edge-sa-view-binding \
 kubectl create clusterrolebinding edge-sa-console-reader-binding \
   --clusterrole cloud-console-reader --serviceaccount default:${KSA_NAME}
 kubectl create clusterrolebinding another-binding \
-  --clusterrole cluster-admin --serviceaccount default:edga-sa
+  --clusterrole cluster-admin --serviceaccount default:${KSA_NAME}
```
Comment (Shabirmean) [inline anthos-bm-edge-deployment/scripts/cloud/cnuc-k8s-login-setup.sh:51]: Can we update line 18: `edga-sa` -> `edge-sa`

**Review by Shabirmean — APPROVED** [review]
LGTM! 

Can you make some of the minor suggestions made which are out of the scope of what you have touched but is related

**Comment by liggitt** [comment]
comments addressed
