### PR TITLE
fix: bash trap signal error on gce-tf sample initialization script

### LINKED ISSUE #65: The initialization script for the ABM GCE terraform sample has signal handling errors
#### Issue:
- The `sudo ./run_initialization_checks.sh` step after the terraform script has completed has the following error
- As a result the shell has this script continuously running in the background
- It seems to be from [this function](https://github.com/GoogleCloudPlatform/anthos-samples/blob/master/anthos-bm-gcp-terraform/resources/run_initialization_checks.sh#L90-L95) that sets up signal handling for all the background tasks spawned by this script
```
./run_initialization_checks.sh: line 93: trap: $SIG: invalid signal specification
```

### PR DESCRIPTION
**Pull request by Shabirmean**
### Fixes #65 
- The issue was with bash expansion with single quoted variables

#### Description
- The issue could be fixed by replacing the single quotes with double quotes

#### Change summary
- Add double quotes instead of single quotes

### CODE REVIEW

File: anthos-bm-gcp-terraform/resources/run_initialization_checks.sh [hunk 1]
```diff
@@ -90,7 +90,7 @@ function __cleanup__ () {
 function __trap_with_arg__ () {
   FUNC="$1" ; shift
   for SIG ; do
-    trap '$FUNC $SIG' '$SIG'
+    trap "$FUNC $SIG" "$SIG"
```
Comment (bourgeoisor) [inline anthos-bm-gcp-terraform/resources/run_initialization_checks.sh:93]: Interestingly, the failed test case says otherwise:
```
In ./anthos-bm-gcp-terraform/resources/run_initialization_checks.sh line 93:
    trap "$FUNC $SIG" "$SIG"
          ^---^ SC2064: Use single quotes, otherwise this expands now rather than when signalled.
                ^--^ SC2064: Use single quotes, otherwise this expands now rather than when signalled.
```

Comment (Shabirmean) [reply anthos-bm-gcp-terraform/resources/run_initialization_checks.sh:93]: Ohh probably that's why I had it single quotes in the first place. Let me check

Comment (Shabirmean) [reply anthos-bm-gcp-terraform/resources/run_initialization_checks.sh:94]: I think this still had to be a change done and we might have to skip the linter on this line. The issue is [described here](https://github.com/koalaman/shellcheck/wiki/SC2064). It is applicable when the signal is passed in as is. In our example here we pass in the signals as variables.

So if we use single quotes - allowing on time expansion - will create this error when setting up the trap with a variable. So I have escaped the lint check for this line.

WDYT?

Comment (bourgeoisor) [reply anthos-bm-gcp-terraform/resources/run_initialization_checks.sh:94]: So the idea is that you _do_ want the expansion to occur ASAP, or else we run into issues?
Makes sense to me.

**Review by bourgeoisor — APPROVED** [review]
LGTM
